on:
  workflow_call:

permissions: {}

jobs:
  pinact:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26.3'
          cache: false
      - run: go install github.com/suzuki-shunsuke/pinact/v3/cmd/pinact@v3.10.1
      - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: pinact run --check
