# Trigger a release when a tag that looks like a version number is pushed.
on:
  push:
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

  # Do a test run on PRs that change this file. Doesn't do the actual release.
  pull_request:
    paths:
      - .github/workflows/release.yml

  # Allow manually triggering workflow for testing purposes. As with pull requests, the actual
  # release won't get created.
  workflow_dispatch:

name: Release

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/') }}
  VERSION_TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('test-{0}', github.run_number) }}

jobs:
  release:
    name: ${{ matrix.target }}
    permissions:
      contents: write # Needed for creating releases
    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {target: x86_64-unknown-linux-gnu, runs-on: ubuntu-22.04}
          - {target: aarch64-unknown-linux-gnu, runs-on: ubuntu-22.04-arm}
          - {target: riscv64gc-unknown-linux-gnu, runs-on: ubuntu-22.04-arm, build: zigbuild}

          - {target: x86_64-unknown-linux-musl, runs-on: ubuntu-22.04, musl: true, args: --features=mimalloc}
          - {target: aarch64-unknown-linux-musl, runs-on: ubuntu-22.04-arm, musl: true, args: --features=mimalloc}
          - {target: riscv64gc-unknown-linux-musl, runs-on: ubuntu-22.04-arm, build: zigbuild, args: --features=mimalloc,}

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y clang
        if: matrix.build != 'zigbuild'

      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
        if: matrix.musl == true

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Install Rust toolchain"
        run: |
          rustup toolchain install stable --profile minimal --no-self-update
          rustup target add --toolchain stable ${{ matrix.target }}

      - uses: taiki-e/install-action@7448805ee055a120c89af897795ebbf25efddd52 # cargo-zigbuild
        if: matrix.build == 'zigbuild'
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2.2.1
        if: matrix.build == 'zigbuild'
        with:
          use-cache: false

      - name: Build stage1
        run: cargo +stable build --release

      - name: Switch to linking with sld
        if: matrix.build != 'zigbuild' # zigbuild ignores this config
        run: |
          mkdir -p "$HOME/.cargo"
          SLD="${PWD}/target/release/sld"
          $SLD --version
          echo -e "[target.${{matrix.target}}]\nlinker = \"clang\"\nrustflags = [\"-Clink-arg=--ld-path=$SLD\"]\n" >>"$HOME/.cargo/config.toml"
          cat "$HOME/.cargo/config.toml"

      - name: Build release binary
        run: cargo +stable ${{matrix.build || 'build' }} ${{matrix.args}} --profile dist --target ${{ matrix.target }}

      - name: Create tarballs
        run: |
          n="sld-linker-${VERSION_TAG}-${{ matrix.target }}"
          mkdir "$n"
          cp "target/${{ matrix.target }}/dist/sld" "$n"
          cp README.md LICENSE* "$n"
          readelf -p .comment "$n/sld" | grep "Linker: sld" || echo "::warning::'$n' wasn't linked with sld"
          tar zcf $n.tar.gz $n

      - name: Release # zizmor: ignore[superfluous-actions]
        if: env.IS_RELEASE == 'true'
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          draft: true
          files: |
            sld-linker-*.tar.gz
